"""Second  migration.

Revision ID: 6fac1acfb58e
Revises: f39b6a6a3475
Create Date: 2024-07-17 16:56:30.597884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fac1acfb58e'
down_revision = 'f39b6a6a3475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('milk_production', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))

    with op.batch_alter_table('milk_sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('milk_sales', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    with op.batch_alter_table('milk_production', schema=None) as batch_op:
        batch_op.drop_column('price')
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
